### ISSUE TITLE
Incorrect arguments label in call

### ISSUE THREAD

**Issue by Dbigshooter** [evermeer/AlamofireJsonToObjects#36] opened 2016-10-31 22:52 UTC
Hi there,

I just updated my podfile to use the main branch instead of the Swift3, and now I'm facing several instances of the same error. 

`"Incorrect argument label in call (have 'dictionary:', expected 'coder:')"`

This error occurs in both line 61 and 125.

**Comment by evermeer** [comment] 2016-11-01 06:44
Do you mean you have a compile error in one of the EVReflection files? Is it in EVReflection.swift?

I'm sure that should not happen. Are you on XCode 8.1? Could you try doing a clean build? 

If that does not help, could you try this: remove EVReflection from your pod file, do a `pod update` so that it will be removed from your workspace, then add it back to the pod file and do a `pod update` again.

Yesterday I pushed an update to JSONShootout so that it will also test EVReflection. It's using the latest version and I did not get any compiler issues. See https://github.com/evermeer/JSONShootout

**Comment by Dbigshooter** [comment] 2016-11-01 13:37
The error occours in AlamofireJsonToObjects.swift, but I'll try the things you said later.

**Comment by evermeer** [comment] 2016-11-01 15:03
Ah.. I see there is a problem in AlamoFire. I will try to fix that now...

**Comment by Dbigshooter** [comment] 2016-11-01 16:20
@evermeer Sounds awesome! Much appreciated!

**Comment by evermeer** [comment] 2016-11-01 20:05
I just pushed a fix for this to GitHub and Cocoapods

**Closed as completed** 2016-11-12 12:16 UTC
Labels: Fixed?

**Comment by Alegero** [comment] 2017-04-06 09:40
Issue is still reproducible.

**Comment by evermeer** [comment] 2017-04-06 14:02
@Alegero Could you please switch to the pod EVReflection/Alamofire since it's maintained actively.

Did you add an import AlamofireJsonToObjects?

**Comment by Alegero** [comment] 2017-04-06 14:14
Hi, thanks for tthe answer.

I have switched to EVReflection/Alamofire, but import AlamofireJsonToObjects return error now - “no such module AlamofireJsonToObjects”

**Comment by evermeer** [comment] 2017-04-06 19:34
That's correct, with EVReflection/Alamofire it should be:
import EVReflection

**Comment by pizzimathy** [comment] 2017-11-07 21:13
I have a similar issue with the `EVReflection/XML` extension. Using this in conjunction with `Alamofire`, I have this code:

```
import Alamofire
import EVReflection
...
class Laundry: EVObject {
    var school_name: String?
    var laundry_rooms: [Room] = [];
}
...
class http {
    class func get(view: DataViewController) {
        if view.isXML {
            Alamofire.request(view.uri).responseData{ response in
                if let data = response.data, let xml = String(data: data, encoding: .utf8) {
                    let laundry = Laundry(xml: xml);
                }
            }
        ...
    }
}
```

Xcode throws an error when it tries to compile `Laundry(xml: xml)`, as in the example on `evermeer/EVReflection`, saying that I have an incorrect argument label `xml:` and that `coder:` is expected.

I have installed `EVReflection/XML` by including `pod EVReflection/XML` in my podfile and have gone through the resolution steps outlined in other peoples' issues. Any help is greatly appreciated.
**Edit**: I have posted this in evermeer/EVReflection.

**Comment by evermeer** [comment] 2017-11-08 07:11
@apizzimenti Oeps, sorry, quite some time ago I added some parameters and changed this one to make clear what kind of xml is used. But did not update the documentation (it now is). You should now use:

`let laundry = Laundry(xmlString: xml)`

**Comment by pizzimathy** [comment] 2017-11-08 18:14
Wonderful. Thank you!
